config/routes.rb
KodeKonkurrenz::Application.routes.draw do
  mount Forem::Engine, :at => '/discuss'

  devise_for :users

  root to: "pages#home"
  match '/liveGraph', to: 'pages#liveGraph', via: 'get'
  match '/about' , to: 'pages#about', via: 'get'
  match '/contactUs' , to: 'pages#contactUs', via: 'get'
  match '/privacy' , to: 'pages#privacy', via: 'get'
  match '/discuss' , to: 'pages#discuss', via: 'get'
  match '/problems/practice' , to: 'problems#practice', via: 'get'
  match '/security' , to: 'pages#security', via: 'get'
  match '/termsOfService' , to: 'pages#termsOfService', via: 'get'
  match '/admin', to: 'pages#admin', via: 'get'
  match '/users/:id' => 'users#show', via: 'get', as: :user
  match '/users/edit/:id', to: 'users#edit', via: 'get', as: :edit_user
  match '/users/:id', to: 'users#update', via: 'put' # put req'd for bip

  scope '/games' do
    match '/open', to: 'games#open_games', via: 'get'
    match '/join', to: 'games#join', via: 'post'
    match '/create', to: 'games#create_game', via: 'post'
    match '/create/practice', to: 'games#create_game_practice', via: 'post'
    match '/competition/:id', to: 'games#competition', via: 'get', as: 'competition'
    match '/compile', to: 'games#compile', via: 'post'
    match '/execute', to: 'games#execute', via: 'post'
    match '/status/:id', to: 'games#status', via: 'get'
  end

  scope '/admin' do
    resources :problems, :games
  end

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :player1, class_name: "User"
  belongs_to :player2, class_name: "User"

  def rating
    return -1 unless player1
    player1.rating
  end
  
  def has_ended?
    problem = Problem.find(problem_id)
    return started_at.since(problem.time.minutes).past?
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :load_game, only: :create
  load_and_authorize_resource
  skip_load_and_authorize_resource only: [:competition, :create_game, :open_games, :compile, :execute, :join, :create_game_practice, :status]
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  require('open3')

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show

  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  # Public actions - accessible by non-admins
  def open_games
    #doesn't display practice games open games
    @games = Game.where(winner_id: -1).where(player2_id: -1).where(isPractice: false)
    # render json will include only table attributes without asking for
    # additional details
    render json: @games.as_json(only: [:id, :problem_id, :time_limit, :rating], methods: [:rating])
  end

  def join
    if current_user.nil?
      return render json: { errors: "You must be logged in to join a game!" }, status: 422
    end

    @game = Game.find(params[:id])
    unless @game
      render json: { errors: "Couldn't find game" }, status: 422
      return
    end
    

    if @game.player1_id == current_user.id
      render json: { errors: "Can't join your own game" }, status: 422
      return
    end
    if @game.player2_id != -1
      render json: { errors: "Game is full" }, status: 422
      return
    end

    @game.player2_id = current_user.id

    time = Time.now
    @game.joinTime = time.to_f
    @game.started_at = time
    if @game.save
      render json: { head: "ok" }
    else
      render json: { errors: "Failed to join game" }, status: 422
    end
  end

  # POST /games/create
  def create_game

    if current_user == nil
      flash[:error] = "You must be signed in inorder to create a game!"
      return redirect_to liveGraph_path
    else
      @game = Game.new
    end
    @game.player1_id = current_user.id
    @game.time_limit = params[:time_limit]
    #randomly choose from all possible problem id's
    #Later restrict people from seeing the same problems. 
    @problem = Problem.pluck(:id)
    @problem = @problem.sample(1)
    @game.problem_id = @problem[0]
    @game.rated = params[:rated]
    unless @game.save
      flash[:error] = "couldn't create game =-("
      return redirect_to liveGraph_path
    end
    #show newly created game in live graph. Eventually remove redirection here.
    flash[:success] = "Your game has been created!"
    flash[:gameId] = @game.id
    redirect_to liveGraph_path
  end

  def create_game_practice

    if current_user == nil
      flash[:error] = "You must be signed in inorder to practice!"
      return redirect_to problems_practice_path
    else
      @game = Game.new
    end
    @game.player1_id = current_user.id
    @game.player2_id = -1
    @game.time_limit = params[:time].to_f
    @problem = Problem.where(time: params[:time].to_f).where(difficulty: Integer(params[:difficulty])).where(category: Integer(params[:category])).select(:id).collect(&:id)
    #randomly choose from all possible problem id's
    if @problem.empty?
      flash[:error] = "There is no game with those specifications. Sorry. Try Again!"
      return redirect_to problems_practice_path
    end
    #Later restrict people from seeing the same problems.
    @problem = @problem.sample(1)
    @game.problem_id = @problem[0]
    @game.isPractice = true
    time = Time.now
    @game.joinTime = time.to_f
    unless @game.save
      flash[:error] = "Couldn't create the game =-("
      return redirect_to problems_practice_path
    end
    redirect_to competition_path(@game)
  end

  def competition
    @game = Game.find(params[:id])
    unless current_user.id == @game.player1_id or current_user.id == @game.player2_id
      flash[:error] = "You are not a player in this game!"
      return redirect_to root_path
    end
    if @game.winner_id != -1
      return render text: "This game has ended!"
    end
  end

  # POST /games/compile/
  def compile
    @game = Game.find(params[:game])
    problem = Problem.find(params[:main])
    submitting = params[:submitting]
    directory=params[:session]
    java=params[:code]
    dir = File.dirname("#{Rails.root}/tmp/java/#{directory}/ignored")
    FileUtils.mkdir_p(dir) unless File.directory?(dir)
    File.open(File.join(dir, 'main.java'), 'w') do |f|
      f.puts problem.mainClass
      f.puts
      f.puts java
    end

    Dir.chdir "#{Rails.root}/tmp/java/#{directory}/"
    startTime = Time.now
    compile = %x(javac main.java 2>&1)
    deltaTime = Time.now - startTime
    if compile==""
      success = true
    else
      success = false
    end
    if submitting == "true" and @game.winner_id == -1
      if @game.player1_id == current_user.id
        @game.isSubmitted = true
      elsif @game.player2_id == current_user.id
        @game.isSubmitted2 = true
      end
      @game.save
    
      if success==false
        lose_game
      end
    end
    return render json: {"success"=>success,"output"=>compile,"deltaTime"=>deltaTime}
  end

  # POST /games/execute
  def execute
    @game = Game.find(params[:game])
    submitting = params[:submitting]
    results = private_execution(params[:session])

    if submitting == "true" and @game.winner_id == -1
      if @game.has_ended?
        draw_game
      elsif results[:exitCode] == 120
        win_game
      else
        lose_game
      end
    end

    @game.save

    return render json: {
      output: results[:output],
      error: results[:error],
      deltaTime: results[:deltaTime],
      winnerExists: @game.winner_id == -1 ? false : true,
      winner: @game.winner_id,
      status:results[:exitCode]
    }
  end

  # GET /games/status/:id
  # The client will periodically poll the server to see if the other player has
  # won (or the timer is up).
  def status
    begin
      @game = Game.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      return render json: {status: 'invalid game id'}
    end

    unless defined? @game.started_at
      return render json: {status: 'inactive'}
    end

    if @game.winner_id != -1
      return render json: {status: 'finished', winner: @game.winner_id}
    end

    unless @game.has_ended?
      return render json: {status: 'active'}
    end
    # Do server-side draw calculations if the timer's up and there's no winner
    draw_game if @game.winner_id == -1
  end

  # There's probably a way to rewrite this so that win_game() is called with
  # a user, and then the current lose/win_game() functions are replaced
  # with wrapper functions that call win_game() instead. This works for now,
  # though.

  # Also, these win/lose/draw methods should be in the Game model.
  
  def lose_game
    if @game.isSubmitted
      @game.winner_id = @game.player2_id
      winner = User.find(@game.player2_id)
    elsif @game.isSubmitted2
      @game.winner_id = @game.player1_id
      winner = User.find(@game.player1_id)
    end

    @game.save
    
    update_rating(winner, current_user)
  end

  def win_game
    @game.winner_id = current_user.id

      if @game.isSubmitted
        loser = User.find(@game.player2_id)
      elsif @game.isSubmitted2
        loser = User.find(@game.player1_id)
      end

      @game.save

      update_rating(current_user, loser)
  end

  def draw_game
    # TODO: magic values in the DB are bad, IMO. -1 for unfinished and 0 for
    # draw could be replaced with boolean columns in the future. -js
    @game.winner_id = 0
    update_rating(User.find(@game.player1_id),
                  User.find(@game.player2_id),
                  'draw')
    @game.save
  end

  private
    # winner and loser are User objects, not IDs
    def update_rating(winner, loser, result = 'win')
      if result == 'draw'
        winner_result, loser_result = 0.5, 0.5
      else
        winner_result, loser_result = 1, 0
      end
      winner.rating += calculate_elo(winner_result, winner.rating, loser.rating)
      loser.rating += calculate_elo(loser_result, winner.rating, loser.rating)
      winner.save
      loser.save
    end

    # Formula from here: http://www.chess-mind.com/en/elo-system
    # s = score: 1 = won, 0 = lost, 0.5 = draw
    # f = f factor, us. 400, larger makes it easier to gain/lose points
    def calculate_elo(s, score1, score2)
      d = (score1 - score2).abs
      f = 400
      
      k = if score1 > 2400 and score2 > 2400
            16
          elsif score1 < 2100 or score2 < 2100
            32
          else
            24
          end

      dElo = (k * (s - (1 / (10 ** ((-d / f) + 1)))))
    end

    def private_execution(directory)
      Dir.chdir "#{Rails.root}/tmp/java/#{directory}/"
      startTime = Time.now
      cmd ='timelimit -t 10 java main'
      results = Open3.popen3(cmd) do |i,o,e,t|
        output=o.read

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_limit %><br>
    <%= f.text_field :time_limit %>
  </div>
  <div class="field">
    <%= f.label :player1_id %><br>
    <%= f.number_field :player1_id %>
  </div>
  <div class="field">
    <%= f.label :player2_id %><br>
    <%= f.number_field :player2_id %>
  </div>
  <div class="field">
    <%= f.label :problem_id %><br>
    <%= f.number_field :problem_id %>
  </div>
  <div class="field">
    <%= f.label :winner_id %><br>
    <%= f.number_field :winner_id %>
  </div>
  <div class="field">
    <%= f.label :isPractice %><br>
    <%= f.number_field :isPractice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/competition.html.erb
<%#need to add the ability to handle practice problems. after a game is done set isPractice to false again%>
<div class="modal hide fade" id="gameOverModal">
	<div class="modal-header text-center">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3>Game Over</h3>
	</div>
	<div class="modal-body text-center">
	</div>
	<div class="modal-footer">
		<a href="/liveGraph" class="btn btn-primary pull-right">play another game</a>
	</div>
</div>
<% problem = Problem.find(@game.problem_id)%>

<div class="competition-div" id="competition-div">
	<div id="editor"></div>
	<div class="well well-small" id="console">
		<strong>Console:</strong>
		<i class="icon-chevron-up pull-right" id="toggleConsole"></i>
		<div id="consoleContent" class="well well-small">
		</div>
	</div>
	<div id="sideBar">
		<div class="well well-small text-center" id="timer">
       			<strong>&nbsp;</strong>
		</div>
		<div class="tabbable well well-small">
			<strong>Description:</strong>
			<div class="well well-small" id="challengeDescription">
              <p> <%=problem.description %></p>
			</div>
		</div>
		<div class="btn-group text-center" id="submissionBtns">
			<button type="button" class="btn btn-large" id="checkBtn">Check</button>
			<button type="button" class="btn btn-large" id="submitBtn">Submit</button>
		</div>
	</div>
</div>
<script>
	disableButtons;
	var editor = ace.edit("editor");
	editor.setTheme("ace/theme/clouds");
	editor.getSession().setMode("ace/mode/java");
	editor.setValue("<%=problem.templateClass%>");

	var secondsLeft = <%=(problem.time*60 - (Time.now.to_f - @game.joinTime.to_f)).round%>;
	var randomString = '<%=	o = [('a'..'z'), ('A'..'Z'),(0..9)].map { |i| i.to_a }.flatten
				(0...20).map{ o[rand(o.length)] }.join%>';
	var activeEvent=false;
	var consoleVisible = false;

	var dotty;

	<% if @game.winner_id != -1 %>
		enableButtons;
	<%end%>
	
	function disableButtons(){
		activeEvent=true
		$('#checkBtn').addClass('disabled');
		$('#submitBtn').addClass('disabled');	
	}

	function enableButtons(){
		activeEvent=false
		$('#checkBtn').removeClass('disabled');
		$('#submitBtn').removeClass('disabled');	
	}

	function gameOver(winner){
		$("#gameOverModal").modal('show');
		$("#gameOverModal > .modal-body").html("<h4>"+winner+"</h4>");
		clearInterval(timInt);
		clearInterval(window.statusInterval);
	}

  function handleWinnerID(ID) {
    if (ID == 0) {
      gameOver("It's a draw");
    } else if (ID != <%= current_user.id %>) {
      gameOver("You lose!");
    } else if (ID == <%= current_user.id %>) {
      gameOver("You win!");
    } else {
      // This code should never be reached (famous last words)!
      alert("Hey guys we got a big error here");
    } 
  } 

	function timerInterval(){
		return window.setInterval(function(){
			secondsLeft--;
			if (secondsLeft<0){
				window.clearInterval(timInt);
				disableButtons;
			}else{
				var minutes = Math.floor(secondsLeft/60);
				var seconds = ((secondsLeft%60)<10) ? '0'+secondsLeft%60 : secondsLeft%60;  
				$('#timer>strong').text(minutes+':'+seconds);
			}
		},1000);
	}
	var timInt = timerInterval();

  function getGameStatus() {
    $.get('/games/status/<%= @game.id %>')
      .done(function(result) {
        if (result.status == 'finished') {
          window.clearInterval(statusInterval);
          handleWinnerID(result.winner);
        }
      });
  }

  window.statusInterval = window.setInterval(getGameStatus, 6000);

	function addDots(){
		return window.setInterval(function(){
			$('#consoleContent').append(".");
		},700);
	}

	function draw() {
		var height=$(window).height();
		var width=$(window).width();
		$('#competition-div').height(height-90);
		$('#competition-div').width(width-30);
		$('#challengeDescription').height($(window).height()-302);
		$('#sideBar').width(width/2.618-63);
		$('#submissionBtns').width(width/2.618-63);
		$('#editor').width(1.618/2.618*width-13);
		$('#test').width(1.618/2.618*width-13);
		$('#console').width(1.618/2.618*width-33);
		if (!consoleVisible){
			$('#editor').height(height-173);
			$('#console').height(20);
		}else{
			$('#editor').height(1.618/2.618*(height-120)-7);
			$('#console').height(1/2.618*(height-120)-28);
			$('#consoleContent').height(1/2.618*(height-120)-68);
		}
		editor.resize()
	};
	$(window).resize(draw);
	draw();

	function doAjax(action,isSubmission,customFunc){
		submission = {"<%= request_forgery_protection_token.to_s%>":"<%= form_authenticity_token%>",
			"session":randomString,
			"code":editor.getValue(),
			"player": <%= current_user.id%>,
			"game": <%= @game.id%>,
			"main": <%= @game.problem_id%>,
			"submitting": isSubmission}
		$.ajax({
			type:"POST",
			url:'/games/'+action,
			data: submission,
			success: function(result){
				customFunc(isSubmission,result);
			}
		});
	}
	$('#checkBtn').click(function(){
		if (!activeEvent) {compilation(false);};
	});

	$('#submitBtn').click(function(){
		if (!activeEvent) {compilation(true);};
	});

	function compilation(isSubmission){
		disableButtons();
		showConsole();
		$('#consoleContent').text("Compiling");
		dotty = addDots();
		doAjax('compile',isSubmission,function(isSubmission,result){
			window.clearInterval(dotty);
			if(result.success){
				$('#consoleContent').append(' Compilation complete in '+Math.round(result.deltaTime)+'ms<br />Executing');
				dotty = addDots();
				doAjax('execute',isSubmission,execution);
			}else{
				$('#consoleContent').append(' Compilation failed:');
				consoleWriter(result.output,'red');
				if(!isSubmission){enableButtons();};
			}
		});
	}

	function execution(isSubmission,result){
		window.clearInterval(dotty);
		consoleWriter(result.output,'black');
		if(result.error==""){
			$('#consoleContent').append('<br />Execution complete in '+Math.round(result.deltaTime)+'ms');
		}else{
			consoleWriter(result.error,'red');
		}
		if(!isSubmission){
      enableButtons();
      return;
      }

    window.clearInterval(statusInterval);
    handleWinnerID(result.winner);
	}

	function consoleWriter(text,color){
		var spl = text.split("\n");
		for(var i=0;i<spl.length-1;i++){
			var leadingSpace="";
			var line=spl[i];
			var j = 0;
			while(line.charAt(0)=="\t"||line.charAt(0)==" "){
				if(line.charAt(0)=="\t"){
					leadingSpace+="&nbsp;&nbsp;&nbsp;&nbsp;";
				}else{
					if(j%2==0){
						leadingSpace+="&nbsp;";
					}
					j++;
				}
				line=line.slice(1);
			}
			$('#consoleContent').append('<br />'+leadingSpace+'<code style="color:'+color+'"></code>');
			$('#consoleContent>code').last().text(line);
		}
	}

	$('#toggleConsole').click(function(){
		if(consoleVisible){
			hideConsole();
		}else{
			showConsole();
		}
	});
	
	function showConsole(){
		$('#toggleConsole').removeClass('icon-chevron-up').addClass('icon-chevron-down');
		$('#consoleContent').css("display","block");
		consoleVisible=true
		draw();
	}
	function hideConsole(){
		$('#toggleConsole').removeClass('icon-chevron-down').addClass('icon-chevron-up');
		$('#consoleContent').css("display","none");
		consoleVisible=false
		draw();

	}
</script>

app/views/games/edit.html.erb
<div class="admin-div">
<div class="well">
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>
</div>
</div>

app/views/games/index.html.erb
<div class="admin-div">
<div class="well">
<h1>Listing games</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Time limit</th>
      <th>Player1</th>
      <th>Player2</th>
      <th>Problem</th>
      <th>Winner</th>
      <th>isPractice</th>
      <th>isSubmitted</th>
      <th>isSubmitted2</th>
      <th>joinTime</th>
      <th>started_at</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.id %>
        <td><%= game.time_limit %></td>
        <td><%= game.player1_id %></td>
        <td><%= game.player2_id %></td>
        <td><%= game.problem_id %></td>
        <td><%= game.winner_id %></td>
        <td><%= game.isPractice %></td>
        <td><%= game.isSubmitted %></td>
        <td><%= game.isSubmitted2 %></td>
        <td><%= game.joinTime %></td>
        <td><%= game.started_at %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <%= form_tag({controller: "games", action: "join"}, method: "post") do  %>
            <%= hidden_field_tag(:id, game.id) %>
            <%= submit_tag("Join") %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>
</div>
</div>

app/views/games/new.html.erb
<div class="admin-div">
<div class="well">
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>
</div>
</div>

app/views/games/show.html.erb
<div class="admin-div">
<div class="well">
<p id="notice"><%= notice %></p>

<p>
  <strong>Time limit:</strong>
  <%= @game.time_limit %>
</p>

<p>
  <strong>Player1:</strong>
  <%= @game.player1_id %>
</p>

<p>
  <strong>Player2:</strong>
  <%= @game.player2_id %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @game.problem_id %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @game.winner_id %>
</p>
<p>
  <strong>Practice:</strong>
  <%= @game.isPractice %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>
</div>
</div>